In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.23.4


Create a numpy array of size 10, filled with zeros.

Create a numpy array with values ranging from 10 to 49

Create a numpy matrix of 2*2 integers, filled with ones.

Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
np.zeros(10)
np.arange(10,49)
# np.array([np.ones(2),np.ones(2)])
np.ones([2,2], dtype=int)
# p.array([np.ones(3), np.ones(3)], dtype=float)
np.ones([3,2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [15]:
X = np.arange(4, dtype=int)
# X[:] = 1
np.ones_like(X)

X = np.array([[1,2,3], [4,5,6]], dtype=int)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

Create a numpy matrix of 4*4 integers, filled with fives.

In [16]:
np.ones([4,4], dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [18]:
X = np.array([[2,3], [6,2]], dtype=int)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

Create a numpy array, filled with 3 random integer values between 1 and 10.

Create a 3*3*3 numpy matrix, filled with random float values.

Given the X python list convert it to an Y numpy array

In [33]:
np.identity(3)
np.random.randint(10,size=3)
np.random.randn(3,3,3) # 0 to 1 floats

X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


Given the X numpy array, make a copy and store it on Y.

Create a numpy array with numbers from 1 to 10

Create a numpy array with the odd numbers between 1 to 10

Create a numpy array with numbers from 1 to 10, in descending order.

In [42]:
X = np.array([5,2,3], dtype=int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

np.arange(1,11)
np.arange(2,10,2)
np.arange(1, 11)[::-1]

[5 2 3] 2195676116720
[5 2 3] 2195676117872


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

Show the memory size of the given Z numpy matrix

In [44]:
print(np.arange(9).reshape(3,3))

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
800 bytes


Given the X numpy array, show it's first element
Given the X numpy array, show it's last element
Given the X numpy array, show it's first three elements
Given the X numpy array, show all middle elements
Given the X numpy array, show the elements in reverse position
Given the X numpy array, show the elements in an odd position

In [48]:
X = np.array(['A','B','C','D','E'])
print(X[0], X[-1], X[0:3], X[1:-1],X[::-1],X[::2])

A E ['A' 'B' 'C'] ['B' 'C' 'D'] ['E' 'D' 'C' 'B' 'A'] ['A' 'C' 'E']


Given the X numpy matrix, show the first row elements
Given the X numpy matrix, show the last row elements
Given the X numpy matrix, show the first element on first row
Given the X numpy matrix, show the last element on last row
Given the X numpy matrix, show the middle row elements
Given the X numpy matrix, show the first two elements on the first two rows
Given the X numpy matrix, show the last two elements on the last two rows

In [63]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(X[0])
print(X[-1])
print(X[0,0])
print(X[-1,-1])
print(X[1:3])
print(X[:2,:2])
print(X[2:,2:])

[1 2 3 4]
[13 14 15 16]
1
16
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[11 12]
 [15 16]]


Convert the given integer numpy array to float
Reverse the given numpy array (first element becomes last)

In [65]:
X = [-5, -3, 0, 10, 40]
X = np.array(X, dtype=float)
X[::-1]

array([40., 10.,  0., -3., -5.])

Order (sort) the given numpy array

In [71]:
X = [0, 10, -5, 40, -3]
X.sort()
X

[-5, -3, 0, 10, 40]

Given the X numpy array, set the fifth element equal to 1

In [73]:
X = np.zeros(10)
X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Given the X numpy array, change the 50 with a 40

In [74]:
X = np.array([10, 20, 30, 50])
X[3] = 40
X

array([10, 20, 30, 40])

Given the X numpy matrix, change the last row with all 1
Given the X numpy matrix, change the last item on the last row with a 0
Given the X numpy matrix, add 5 to every element

In [78]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = 1
X[-1,-1] = 0
X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 6,  6,  6,  5]])

Given the X numpy array, make a mask showing negative elements
Given the X numpy array, get the negative elements
Given the X numpy array, get numbers higher than 5
Given the X numpy array, get numbers higher than the elements mean
Given the X numpy array, get numbers equal to 2 or 10

In [88]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X<0
print(mask)
print(X[X < 0])
print(X[X>5])
print(X[X>X.mean()])
print(X[(X==0) | (X==10)])

[ True False False  True False False False False  True False]
[-1 -4 -9]
[ 6 10]
[ 2  5  6 10]
[ 0  0  0 10]


Given the X numpy array, return True if none of its elements is zero
Given the X numpy array, return True if any of its elements is zero

In [91]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
print(X.all(), X.any())

False True


Given the X numpy array, show the sum of its elements

In [83]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X.sum()

43

Given the X numpy array, show the mean value of its elements

In [79]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.mean()

3.7

Given the X numpy matrix, show the sum of its columns
Given the X numpy matrix, show the mean value of its rows

In [82]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

Given the X numpy array, show the max value of its elements

In [80]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.max()

10

In [96]:
np.random.normal(size=2)
np.random.randint(10,size=3)
np.random.random(size=2)
np.random.rand(2,6)

array([[0.7756423 , 0.22840895, 0.84229956, 0.46200764, 0.33184421,
        0.09821105],
       [0.70885669, 0.65738941, 0.23877619, 0.62867384, 0.67890763,
        0.28143528]])