Zadanie 1.
Stwórz losową tablicę 10,000 liczb, następnie do każdego elementu dodaj 1. Następnie napisz dokładnie tę samą funkcję używając numpy i jego tablic. Porównaj czas działania swoich rozwiązań.

In [10]:
import random
import numpy as np

UsageError: Line magic function `%%timeit` not found.


In [11]:
%%timeit
Tab = [random.randint(0,10000) + 1 for _ in range(10000)]

9.58 ms ± 306 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
%%timeit
npTab = np.random.rand(10000) + 1

82.9 µs ± 2.66 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Zadanie 2.
Napisz funkcje obliczajaca sin(x)+cos(x) dla kazdego elementu tablicy 10,000 losowych liczb używając pętli oraz używając numpy, porownaj ich szybkość podobnie jak w poprzednim zadaniu.

In [ ]:
from math import sin, cos

In [17]:
%%timeit
sin_cos = [random.randint(0,100) for x in range(10000)]
for i, x in enumerate(sin_cos):
    sin_cos[i] = sin(x) + cos(x)

12.8 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
%%timeit
sin_cos = np.random.rand(10000)
sin_cos = np.sin(sin_cos) + np.cos(sin_cos)

216 µs ± 6.71 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Zadanie 3.
Napisz wydajniejszą forme następujących funkcji. Dopisz do każdej test potwierdzający szybkość zaproponowanego rozwiązania.

In [ ]:
%%timeit
def cube_sum(x):
    """Zwraca sume szescianow elementow"""
    result = 0
    for i in range(len(x)):
        result += x[i] ** 3
    return result

In [ ]:
%%timeit
def almost_variance(x):
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    m = sum(x) / len(x)
    result = 0
    for i in range(len(x)):
        result += (x[i] - m) ** 4
    result /= len(x)
    return result

In [ ]:
%%timeit
def cube_sum(x):
    return np.power(x,3).sum()

In [ ]:
%%timeit
def almost_variance(x):
    return np.power(x-x.mean,4).mean

Zadanie 4.
Wykorzystujac broadcasting (patrz na rysunek poniżej) stwórz tabliczkę mnożenia tzn. tablice A taka, ze
Aij=i*j dla i,j w {1,...,10}

Czy potrafisz wykonać to jednym poleceniem, nie używajac przy tym petli/comprehensions?

In [16]:
tab = np.arange(1,11)
print(tab * tab.reshape(10,1))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Zadanie 5.
Wygeneruj losową tablice 10 x 5, która będzie reprezentować 10 punktów w 5 wymiarowej przestrzeni. Napisz funkcje, która policzy odleglość euklidesową pomiędzy każdą parą punktów, czy potrafisz zrobić to bez użycia żadnych pętli/comprehensions?

Przypomnienie, dla dwóch wektorów -> lab11

In [27]:
def dist(d):
    return np.square(d.reshape(10,1,5) - d.reshape(1,10,5)).sum(-1)

def dist_py(d):
    res = np.zeros((len(d),len(d)))
    for i in range(len(d)):
        for j in range(len(d)):
            res[i][j] = np.square(d[i] - d[j]).sum()
    return res


In [29]:
data = np.random.rand(10,5)
assert np.allclose(dist(data), dist_py(data))

Zadanie 6.

In [25]:
rand_arr = np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])

def whiten_np(x):
    return(x - np.mean(x, axis=0) / np.std(x, axis=0))

print(whiten_np(rand_arr))
print(np.std(whiten_np(rand_arr), axis=0))
print(np.mean(whiten_np(rand_arr), axis=0))

[[-1.41421356 -0.76776695]
 [ 0.58578644  1.23223305]
 [ 2.58578644  3.23223305]
 [ 4.58578644  5.23223305]
 [ 6.58578644  7.23223305]]
[2.82842712 2.82842712]
[2.58578644 3.23223305]


Zadanie 7.

In [21]:
def closest(x, A):
    return A[np.argmin(np.abs(A-x))]

closest(1.5, np.array([1,-4,3]))

1

Zadanie 8.

In [30]:
def poly(x, a):
    return np.sum(np.cumprod(np.full_like(a,x))/x*a)

In [32]:
k = 10
x, a = np.random.rand(), np.random.rand(k)
assert np.isclose(poly(x,a),np.poly1d(a[::-1])(x)), f'{poly(x,a)} != {np.poly1d(a)(x)}'

Zadanie 9.

In [40]:
import matplotlib.pyplot as plt
from PIL import Image
img  = Image.open('img.jpg') 
img1 = 0.2126 * img[:,:,0] + 0.7152 * img[:,:,1] + 0.0722 * img[:,:,2]
plt.imshow(img1, camp='gray')

TypeError: 'WebPImageFile' object is not subscriptable

Zadanie 10.

In [35]:
def interpol(x1,x2,lambdas):
    lambdas = lambdas.reshape((len(lambdas),1))
    return x1*lambdas + (1-lambdas)*x2